### PR TITLE
263 move data contribution guide

### LINKED ISSUE #263: Move data contribution guide
Move data contribution guide with Girder from feelpp/toolbox to feelpp/book.feelpp.org

### PR DESCRIPTION
**Pull request by lberti**
- move data contribution Guide with Girder from feelpp/toolbox to book.feelpp.org
- use `partials` of the "Data manual" from book.feelpp.org to keep showing the Data contribution guide inside the "Toolbox contribution guide" manual and the "Data manual"

- closes #263

### CODE REVIEW

**Review by prudhomm — APPROVED** [review]

**Comment by prudhomm** [comment]
screenshot

it seems that the new girder partial does not appear on the Data manual. does it ? Perhaps in Data Storage.
Also there was a discussion to use feelpp RemoteData to use Girder rather than the Girder API  itself directly 
<details><summary>Browser metadata</summary>





```
Path:      /data/
Browser:   Chrome 115.0.0.0 on Mac OS 10.15.7
Viewport:  1728 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-264--adoring-edison-f92f3c.netlify.app%2Fdata%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=115.0&resolution=1728x904&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-264--adoring-edison-f92f3c.netlify.app/data/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=64f65b758d93b70008eebfa2&commentID=64f65d852525ca2aa89820c7&resolution=resolved)

**Comment by lberti** [comment]
@prudhomm I have made some modifications in the navigation bar in order to put the pages under Data storage/Girder, and added a section for feelpp_remotedata to the already available documentation including Girder API.

Locally I can see the modifications if I specify the branches to be downloaded in the `site.yml` file. Maybe you can't see the menu here because of some configuration issue with Netlify?

**Comment by lberti** [comment]
It also seems that on some `push`, buildkite jobs are triggered (which causes the red crosses to appear next to the commits)

**Comment by lberti** [comment]
@prudhomm I can see the modifications locally. I wonder if there is a problem with the specification of branches in `site.yml` for the Netlify preview, as for example here

> - url: https://github.com/feelpp/toolbox
    branches: [develop]
    tags:
    - v0.110
    - v0.109
    start_path: examples
  
or here 
> - url: https://github.com/feelpp/toolbox
>     branches: [develop]
>     start_path: toolboxes

There seem to be an analogous problem with this other [pull request](https://github.com/feelpp/toolbox/pull/188) in feelpp/toolbox that is not able to properly find the partials that come from this PR.

**Comment by prudhomm** [comment]
I am looking into this, thanks

**Pull request merged**
