### PR TITLE
Add HDG toolbox for mixedpoisson

### PR DESCRIPTION
**Pull request by romainhild**

### CODE REVIEW

**Comment by romainhild** [comment]
@prudhomm We said that we would add the benchmarks somewhere else, but in the other toolboxes, it is directly there.
How should we do ? Add it after the description of the model or put it somewhere else (where?) ?

**Comment by prudhomm** [comment]
@romainhild I haven't changed the other documents, however all the benchmarks are in separate files, they are just `include::`d

**Comment by prudhomm** [comment]
how about the theoretical notes on HDG ? did you move them already ?

**Comment by romainhild** [comment]
No I have not move the theoretical notes. Where should I put them ? in math ?
Ok, for the hdg benchmarks, maybe I'll create a folder and put them in it, and include them from the toolbox description.

**Pull request merged**
