### PR TITLE
Update permalink + move back to benchmarks

### PR DESCRIPTION
**Pull request by gdolle**
- Move back benchmarks under benchmarks directory (consistency => avoid confusion in the future)
- Update permalink  `/toolbox/cfd `  `/benchmarks/cfd` and for toolbox `/benchmarks/cfd/toolbox/`
   Each benchmarks permalink will be prefix by bm and suffixed by benchmark number,  `/benchmarks/cfd/toolbox/bm-1/`,  `/benchmarks/cfd/toolbox/bm-2`, ...

TIP: In the future for applications, `/benchmarks/cfd/applications/`, ... `/benchmarks/cfd/testsuite/`, etc ...

- Add comments to explain what to not do in headers
- Update CONTRIBUTING

Bug/Known issues:

- Update headers with ifndef path to be compatible with github.
- Update relative path using page-root variable. (Wait for jekyll-asciidoc issues)

### CODE REVIEW

**Comment by prudhomm** [comment]
@gdolle do you have a script to generate singularity container from docker ?

**Comment by prudhomm** [comment]
@gdolle shouldn't we have something similar to mso4sc to handle images eg in github ?

**Comment by gdolle** [comment]
@prudhomm I'm currently doing the singularity script.

**Comment by gdolle** [comment]
@prudhomm I agree for the images. I just didn't have the time to modify all image. It's an intermediate PR. ;)

**Comment by prudhomm** [comment]
ok nice job anyway ! :)

I am almost done with the changes in docker with feelpp install changes

**Pull request merged**
